spring:
  application:
    name: aws-with-java-sdk-and-spring
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
      instance-profile: true
      use-default-aws-credentials-chain: true
    region:
      static: eu-west-3
    stack:
      auto: false